AWSTemplateFormatVersion: 2010-09-09
Description: EC2 instances setup 
  
Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: must be a valid EC2 instance type

  LatestAmiId:
    Type:  AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance.


Resources:
  WebServer1:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          sudo amazon-linux-extras install -y nginx1
          sudo service nginx start
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      SubnetId: !ImportValue VPC-Subnet1Public
      SecurityGroupIds:
        - !ImportValue Security-AppSecurityGroup
      Tags: 
        - Key: Name
          Value: AppNginxInstance1    

  DBServer1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      SubnetId: !ImportValue VPC-Subnet1Private
      SecurityGroupIds:
        - !ImportValue Security-DBSecurityGroup
      Tags: 
        - Key: Name
          Value: AppNginxInstance1 

  WebServer2:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          sudo amazon-linux-extras install -y nginx1
          sudo service nginx start
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      SubnetId: !ImportValue VPC-Subnet2Public
      SecurityGroupIds:
        - !ImportValue Security-AppSecurityGroup
      Tags: 
        - Key: Name
          Value: AppNginxInstance1    

  DBServer2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref LatestAmiId
      SubnetId: !ImportValue VPC-Subnet2Private
      SecurityGroupIds:
        - !ImportValue Security-DBSecurityGroup
      Tags: 
        - Key: Name
          Value: AppNginxInstance1 

  
Outputs:
  AppServer1Id:
    Description: Web Server in AZ 1 ID
    Value: !Ref WebServer1

  DBServer1Id:
    Description: Database server in AZ 1 ID
    Value: !Ref DBServer1

  AppServer2Id:
    Description: Web Server in AZ 2 ID
    Value: !Ref WebServer2

  DBServer2Id:
    Description: Database server in AZ 2 ID
    Value: !Ref DBServer2

