

AWSTemplateFormatVersion: 2010-09-09
Description: |
  Standalone security group

Parameters:

  
Resources:
  SecurityGroupHTTPFromWorld:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows port 80 from the world
      GroupName: !Sub 'HTTPFromAnywhere-${AWS::StackId}'
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 2049
          ToPort: 2049
          CidrIp: 0.0.0.0/0

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: RDSSecurityGroup
      GroupDescription: RDS Security Group
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref SecurityGroupHTTPFromWorld

Outputs:
  AppSecurityGroupId:
    Value: !GetAtt SecurityGroupHTTPFromWorld.GroupId
    Export: 
      Name: !Sub '${AWS::StackName}-AppSecurityGroup'

  DBSecurityGroupId:
    Value: !GetAtt DBSecurityGroup.GroupId
    Export: 
      Name: !Sub '${AWS::StackName}-DBSecurityGroup'