AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with 2 Availability Zones with 2 EC2 instances in each AZ

Mappings:
  InstanceTypeArchitectures:
    t2.micro:
      Architecture: HVM64

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: must be a valid EC2 instance type

  Region:
    Description: AWS region
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
    ConstraintDescription: only to be used in us-east-1

Resources:
  FHVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true

  FHInternetGateway:
    Type: "AWS::EC2::InternetGateway"

  AttachGateway:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId:
        Ref: "FHVPC"
      InternetGatewayId:
        Ref: "FHInternetGateway"

  MySubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: FHVPC
      CidrBlock: '10.0.0.0/24'
      AvailabilityZone: 'us-east-1a'

  MySubnet2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: FHVPC
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: 'us-east-1b'

  MyInstance1A1:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Ref: MySubnet1
      Architecture: !FindInMap [InstanceTypeArchitectures, !Ref InstanceType, !Ref Region]

  MyInstance1A2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Ref: MySubnet1

  MyInstance2A1:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Ref: MySubnet2

  MyInstance2A2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Ref: MySubnet2

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref FHVPC

  Subnet1Id:
    Description: Subnet 1 ID
    Value: !Ref MySubnet1

  Subnet2Id:
    Description: Subnet 2 ID
    Value: !Ref MySubnet2

  Instance1A1Id:
    Description: EC2 Instance 1 in Availability Zone 1 ID
    Value: !Ref MyInstance1A1

  Instance1A2Id:
    Description: EC2 Instance 2 in Availability Zone 1 ID
    Value: !Ref MyInstance1A2

  Instance2A1Id:
    Description: EC2 Instance 1 in Availability Zone 2 ID
    Value: !Ref MyInstance2A1

  Instance2A2Id:
    Description: EC2 Instance 2 in Availability Zone 2 ID
    Value: !Ref MyInstance2A2