AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with 2 Availability Zones with 2 EC2 instances in each AZ

Mappings:
  InstanceTypeArchitectures:
    t2.micro:
      Architecture: HVM64

Parameters:
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: must be a valid EC2 instance type

  Region:
    Description: AWS region
    Type: String
    Default: us-east-1
    AllowedValues:
      - us-east-1
    ConstraintDescription: only to be used in us-east-1

Resources:
  FHVPC1:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true

  FHInternetGateway:
    Type: "AWS::EC2::InternetGateway"

  AttachGateway:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      VpcId:
        Ref: "FHVPC1"
      InternetGatewayId:
        Ref: "FHInternetGateway"

  InternalSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: FHVPC1
      CidrBlock: '10.0.0.0/24'
      AvailabilityZone: 'us-east-1a'

  AppSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId:
        Ref: FHVPC1
      CidrBlock: '10.0.1.0/24'
      AvailabilityZone: 'us-east-1b'

  WebServer1:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Ref: AppSubnet1
      Architecture: !FindInMap [InstanceTypeArchitectures, !Ref InstanceType, !Ref Region]

  DBServer1:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Ref: AppSubnet1
      Architecture: !FindInMap [InstanceTypeArchitectures, !Ref InstanceType, !Ref Region]

  JumpBox:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Ref: InternalSubnet1
      Architecture: !FindInMap [InstanceTypeArchitectures, !Ref InstanceType, !Ref Region]

  WebServer2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      SubnetId:
        Ref: InternalSubnet1
      Architecture: !FindInMap [InstanceTypeArchitectures, !Ref InstanceType, !Ref Region]

Outputs:
  VPCId:
    Description: VPC1 ID
    Value: !Ref FHVPC1

  Subnet1Id:
    Description: internal Subnet ID
    Value: !Ref InternalSubnet1

  Subnet2Id:
    Description: Application Subnet ID
    Value: !Ref AppSubnet1

  Instance1A1Id:
    Description: Web Server in App AZ ID
    Value: !Ref WebServer1

  Instance1A2Id:
    Description: App Server in Internal AZ ID
    Value: !Ref WebServer2

  Instance2A1Id:
    Description: Database server in App AZ ID
    Value: !Ref DBServer1

  Instance2A2Id:
    Description: Jumpbox in Internal AZ ID
    Value: !Ref JumpBox