AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with 2 Availability Zones

Parameters:
  Region:
    Description: AWS region
    Type: String
    Default: us-east-2
    AllowedValues:
      - us-east-2
    ConstraintDescription: only to be used in us-east-1

Resources:
  FHVPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC

  FHInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: FHVPC1
      InternetGatewayId:
        Ref: FHInternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: MyVPC
    Properties:
      VpcId: !Ref FHVPC1
      Tags:
        - Key: Name
          Value: !Sub ${TagPrefix}-PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    DependsOn: MyVPC
    Properties:
      VpcId: !Ref FHVPC1
      Tags:
        - Key: Name
          Value: !Sub ${TagPrefix}-PrivateRouteTable

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PublicRouteTable
      GatewayId: !Ref FHInternetGateway      

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: 0.0.0.0/0
      RouteTableId: !Ref PrivateRouteTable
      GatewayId: !Ref FHInternetGateway     

  InternalSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: FHVPC1
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-2a
      Tags:
      - Key: Name
        Value: !Sub ${TagPrefix}-PrivateSubnet1 

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: FHVPC1
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-2b
      Tags:
      - Key: Name
        Value: !Sub ${TagPrefix}-PublicSubnet1 

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
      - PublicRouteTable
      - PublicSubnet1
    Properties: 
      RouteTableId: !Ref PublicRouteTable
      SubnetId: !Ref PublicSubnet1

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    DependsOn: 
      - PrivateRouteTable
      - InternalSubnet1
    Properties: 
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref InternalSubnet1

Outputs:
  VPCId:
    Description: VPC1 ID
    Value: !Ref FHVPC1
    Export:
      Name: ExportedVPCID

  Subnet1Id:
    Description: internal Subnet ID
    Value: !Ref InternalSubnet1
    Export:
      Name: ${AWS::StackName}-InternalSubnet

  Subnet2Id:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet1
    Export:
      Name: ${AWS::StackName}-PublicSubnet

