AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with 2 Availability Zones with 2 EC2 instances in each AZ

Parameters:
  Region:
    Description: AWS region
    Type: String
    Default: us-east-2
    AllowedValues:
      - us-east-2
    ConstraintDescription: only to be used in us-east-1

Resources:
  FHVPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  FHInternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: FHVPC1
      InternetGatewayId:
        Ref: FHInternetGateway

  InternalSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: FHVPC1
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: us-east-2a

  AppSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: FHVPC1
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-2b


Outputs:
  VPCId:
    Description: VPC1 ID
    Value: !Ref FHVPC1
    Export:
      Name: ExportedVPCID

  Subnet1Id:
    Description: internal Subnet ID
    Value: !Ref InternalSubnet1
    Export:
      Name: ExportedSubnet1ID

  Subnet2Id:
    Description: Application Subnet ID
    Value: !Ref AppSubnet1
    Export:
      Name: ExportedSubnet2ID

